-- MySQL Script generated by MySQL Workbench
-- Sat Mar  5 18:53:04 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- -----------------------------------------------------
-- Schema api_hackaton
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS api_hackathon DEFAULT CHARACTER SET utf8 ;
USE api_hackathon ;

-- -----------------------------------------------------
-- Table hackathon
-- -----------------------------------------------------
DROP TABLE IF EXISTS hackathons ;

CREATE TABLE IF NOT EXISTS hackathons (
  id INT NOT NULL AUTO_INCREMENT,
  country VARCHAR(45) NOT NULL,
  state VARCHAR(45) NOT NULL,
  hackathon_year VARCHAR(45) NOT NULL,
  created_at TIME,
  updated_at TIME,
  deleted_at TIME,
  PRIMARY KEY (id))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table developments
-- -----------------------------------------------------
DROP TABLE IF EXISTS developments ;

CREATE TABLE IF NOT EXISTS developments (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) NOT NULL,
  description VARCHAR(255) NOT NULL,
  score FLOAT NOT NULL,
  hackathon_id INT NOT NULL,
  created_at TIME,
  updated_at TIME,
  deleted_at TIME,
  PRIMARY KEY (id),
  CONSTRAINT fk_developments_hackathons1
    FOREIGN KEY (hackathon_id)
    REFERENCES hackathons (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table developer
-- -----------------------------------------------------
DROP TABLE IF EXISTS developers ;

CREATE TABLE IF NOT EXISTS developers (
  id INT NOT NULL AUTO_INCREMENT,
  first_name VARCHAR(45) NOT NULL,
  last_name VARCHAR(45) NOT NULL,
  email VARCHAR(45) NOT NULL,
  development_id INT NOT NULL,
  created_at TIME,
  updated_at TIME,
  deleted_at TIME,
  PRIMARY KEY (id),
    FOREIGN KEY (development_id)
    REFERENCES developments(id))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table api_hackaton.users
-- -----------------------------------------------------
DROP TABLE IF EXISTS users ;

CREATE TABLE IF NOT EXISTS users (
  id INT NOT NULL AUTO_INCREMENT,
  email VARCHAR(100) NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIME,
  updated_at TIME,
  deleted_at TIME,
  PRIMARY KEY (id),
  UNIQUE INDEX email_UNIQUE (email ASC))
ENGINE = InnoDB;
