INSERT INTO hackathons (country,state,hackathon_year) VALUES ('United States','Chicago','2022');
INSERT INTO hackathons (country,state,hackathon_year) VALUES ('United States','Miami','2022');
INSERT INTO hackathons (country,state,hackathon_year) VALUES ('United States','New York','2022');

INSERT INTO developments (name,description,score, hackathon_id) VALUES ('some','lorem_ipsum',200,1);
INSERT INTO developments (name,description,score, hackathon_id) VALUES ('team','lorem_ipsum',150,1);
INSERT INTO developments (name,description,score, hackathon_id) VALUES ('namethat','lorem_ipsum',230,1);
INSERT INTO developments (name,description,score, hackathon_id) VALUES ('imclearly','lorem_ipsum',18,1);
INSERT INTO developments (name,description,score, hackathon_id) VALUES ('inventing','lorem_ipsum',25,1);
INSERT INTO developments (name,description,score, hackathon_id) VALUES ('becauseidont','lorem_ipsum',125,1);
INSERT INTO developments (name,description,score, hackathon_id) VALUES ('know','lorem_ipsum',340,1);
INSERT INTO developments (name,description,score, hackathon_id) VALUES ('whatelse','lorem_ipsum',200,1);
INSERT INTO developments (name,description,score, hackathon_id) VALUES ('toput','lorem_ipsum',220,1);

INSERT INTO developments (name,description,score, hackathon_id) VALUES ('sothisis','lorem_ipsum',200,2);
INSERT INTO developments (name,description,score, hackathon_id) VALUES ('agoodway','lorem_ipsum',150,2);
INSERT INTO developments (name,description,score, hackathon_id) VALUES ('tofill','lorem_ipsum',230,2);
INSERT INTO developments (name,description,score, hackathon_id) VALUES ('mydata','lorem_ipsum',18,2);
INSERT INTO developments (name,description,score, hackathon_id) VALUES ('base','lorem_ipsum',25,2);
INSERT INTO developments (name,description,score, hackathon_id) VALUES ('commodities','lorem_ipsum',125,2);
INSERT INTO developments (name,description,score, hackathon_id) VALUES ('school','lorem_ipsum',121,2);
INSERT INTO developments (name,description,score, hackathon_id) VALUES ('random','lorem_ipsum',90,2);
INSERT INTO developments (name,description,score, hackathon_id) VALUES ('randoname','lorem_ipsum',85,2);

INSERT INTO developments (name,description,score, hackathon_id) VALUES ('anothername','lorem_ipsum',450,3);
INSERT INTO developments (name,description,score, hackathon_id) VALUES ('ofcourse','lorem_ipsum',422,3);
INSERT INTO developments (name,description,score, hackathon_id) VALUES ('daylight','lorem_ipsum',390,3);
INSERT INTO developments (name,description,score, hackathon_id) VALUES ('moon','lorem_ipsum',18,3);
INSERT INTO developments (name,description,score, hackathon_id) VALUES ('sun','lorem_ipsum',400,3);
INSERT INTO developments (name,description,score, hackathon_id) VALUES ('aname','lorem_ipsum',125,3);
INSERT INTO developments (name,description,score, hackathon_id) VALUES ('callers','lorem_ipsum',340,3);
INSERT INTO developments (name,description,score, hackathon_id) VALUES ('dataracing','lorem_ipsum',122,3);
INSERT INTO developments (name,description,score, hackathon_id) VALUES ('goroutines','lorem_ipsum',100,3);

INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Jhon','Smith','jhonsmith@gmail.com',1);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Jhon','William','jhonwilliam@gmail.com',1);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Karen','Gomez','karengomez@gmail.com',1);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Jean','Deep','jeandeep@gmail.com',2);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Jhon','Shal','jhonshal@gmail.com',2);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Jenny','Sean','jeannysean@gmail.com',2);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Jhon','Cork','jhoncork@gmail.com',3);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Marta','Alisson','martaallison@gmail.com',3);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Jhon','Smith','jhonsmith@gmail.com',3);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Abigail','Bored','abigailbored@gmail.com',4);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Jhon','Thise','jhonthise@gmail.com',4);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Loren','Godirio','loren@gmail.com',4);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Jhon','Jhonsson','jj@gmail.com',5);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Jhon','Clark','jclark@gmail.com',5);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Nicolas','William','nicolaswilliam@gmail.com',5);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Jhon','Clark','jcclark@gmail.com',6);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Camile','Sean','camilesean@gmail.com',6);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Lara','Sean','larasean@gmail.com',6);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Jhon','Clark','jcclark@gmail.com',6);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Camile','Sean','camilesean@gmail.com',6);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Lara','Sean','larasean@gmail.com',6);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Jhon','Clark','jcclark@gmail.com',6);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Camile','Sean','camilesean@gmail.com',6);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Lara','Sean','larasean@gmail.com',6);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Ali','Son','alison@gmail.com',7);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Camile','Oldsen','camileoldsen@gmail.com',8);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Lara','Arua','laraarua@gmail.com',9);

INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Jhon','Smith','jhonsmith@gmail.com',10);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Jhon','William','jhonwilliam@gmail.com',10);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Karen','Gomez','karengomez@gmail.com',10);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Jean','Deep','jeandeep@gmail.com',11);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Jhon','Shal','jhonshal@gmail.com',11);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Jenny','Sean','jeannysean@gmail.com',11);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Jhon','Cork','jhoncork@gmail.com',12);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Marta','Alisson','martaallison@gmail.com',12);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Jhon','Smith','jhonsmith@gmail.com',12);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Abigail','Bored','abigailbored@gmail.com',13);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Jhon','Thise','jhonthise@gmail.com',13);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Loren','Godirio','loren@gmail.com',13);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Jhon','Jhonsson','jj@gmail.com',14);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Jhon','Clark','jclark@gmail.com',14);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Nicolas','William','nicolaswilliam@gmail.com',14);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Jhon','Clark','jcclark@gmail.com',15);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Camile','Sean','camilesean@gmail.com',15);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Lara','Sean','larasean@gmail.com',15);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Jhon','Clark','jcclark@gmail.com',16);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Camile','Sean','camilesean@gmail.com',16);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Lara','Sean','larasean@gmail.com',16);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Jhon','Clark','jcclark@gmail.com',16);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Camile','Sean','camilesean@gmail.com',17);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Lara','Sean','larasean@gmail.com',17);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Ali','Son','alison@gmail.com',17);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Camile','Oldsen','camileoldsen@gmail.com',18);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Lara','Arua','laraarua@gmail.com',19);

INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Jhon','Smith','jhonsmith@gmail.com',20);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Jhon','William','jhonwilliam@gmail.com',20);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Karen','Gomez','karengomez@gmail.com',20);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Jean','Deep','jeandeep@gmail.com',21);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Jhon','Shal','jhonshal@gmail.com',21);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Jenny','Sean','jeannysean@gmail.com',21);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Jhon','Cork','jhoncork@gmail.com',22);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Marta','Alisson','martaallison@gmail.com',22);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Jhon','Smith','jhonsmith@gmail.com',22);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Abigail','Bored','abigailbored@gmail.com',23);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Jhon','Thise','jhonthise@gmail.com',23);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Loren','Godirio','loren@gmail.com',23);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Jhon','Jhonsson','jj@gmail.com',24);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Jhon','Clark','jclark@gmail.com',24);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Nicolas','William','nicolaswilliam@gmail.com',24);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Jhon','Clark','jcclark@gmail.com',25);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Camile','Sean','camilesean@gmail.com',25);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Lara','Sean','larasean@gmail.com',25);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Jhon','Clark','jcclark@gmail.com',26);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Camile','Sean','camilesean@gmail.com',26);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Lara','Sean','larasean@gmail.com',26);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Jhon','Clark','jcclark@gmail.com',27);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Camile','Sean','camilesean@gmail.com',27);
INSERT INTO developers (first_name,last_name,email,development_id) VALUES('Lara','Sean','larasean@gmail.com',27);

INSERT INTO users (email,password) VALUES ('admin@admin.com','admin');